# Generated by Django 5.2.6 on 2025-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='product',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='quantity',
            field=models.JSONField(default=list),
        ),
    ]
